### ISSUE TITLE
Trakt tracking random movies

### ISSUE THREAD

**Issue by leemacca13** [umbrellaplug/umbrellaplug.github.io#247]
### Bug

When watching a tv show via umbrella, trakt will trakt the show itself and a random movie at the same time. Marking both as watched when the tv show is completed. 

### Expected Result

Trakt should just track the tv show that I am watching and nothing else. 

### Steps To Reproduce

1. Setup a progress widget in arctic horizon 2
2. Choose a tv show to watch 
3. Whilst tv show is playing login to the trakt website and see the now playing banner. 

### Kodi Version, Type of Device, Logs, Screenshots, and Additional Info

Kodi 20.1
Amazon Fire Cube
Umbrella version 6.6.18
Arctic Horizon 2 Skin

log https://paste.kodi.tv/wupolojinu

I also have the same setup on a fire cube running 19.6 and dont have the issue. So I’m not sure if it’s just a kodi 20 issue. 

### Checklist

- [X] I have included the version of Kodi I'm using and Device in my report.
- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have verified this is not a setting.

**Comment by umbrellaplug** [comment]
Not having this issue on my side. From your logs only thing Umbrella was passing was Picard. Looks related to Seren.

**Comment by leemacca13** [comment]
Thanks for looking into this for me. I tried using seren to see if I could duplicate the issue and it seems to track just the program. 
I also did a fresh install today of kodi 20.1 with just the confluence skin and umbrella installed and the same issue happened again. So I'm unsure if it's an issue with the version of kodi 20.1 I'm using as it's for android.

**Comment by umbrellaplug** [comment]
What are your steps to see a "now playing" banner on trakt?

**Comment by leemacca13** [comment]
> What are your steps to see a "now playing" banner on trakt?

I start an episode and after a few seconds login to the trakt website on my phone and on the Home Screen the you are watching banner appears showing the show I'm watching usually Though since the update to 20.1 it shows a random movie instead.

**Comment by umbrellaplug** [comment]
I'm trying to duplicate your issue but when I open trakt so on my phone I don't have a now playing banner. I have trakt vip and it shows my last watched but no "now playing".

**Comment by leemacca13** [comment]
> I'm trying to duplicate your issue but when I open trakt so on my phone I don't have a now playing banner. I have trakt vip and it shows my last watched but no "now playing". 

![image](https://user-images.githubusercontent.com/85898553/225786684-0b0efc23-b081-4f46-bccc-784cff96c0ba.jpeg)

This is how it looks on my phone when I'm watching a tv show and visit the trakt website.

**Comment by umbrellaplug** [comment]
Strange. I don't get that popup on trakt at all. I need to check my settings I guess. Any settings set in your trakt section of umbrella? Are you using the trakt addon also?

![image](https://user-images.githubusercontent.com/107957815/225789235-2ce83f89-b668-4713-af86-c559176e6485.png)

**Comment by leemacca13** [comment]
That's really strange, as far as I can remember I've always had that pop up. So in the trakt section of umbrella I have the server and general notification boxes ticked as well as direct progress scraping. Browse progress is also ticked, the enable scrobbling is unticked as I usually just use the trakt addon. I also have the trakt upcoming progress prepend date box checked. Everything else is unticked.

**Comment by umbrellaplug** [comment]
After some research, this is caused by the trakt addon. Sorry to keep pointing fingers at other addons here, but it was tough for me to track this down as that's not a functionality I provide. That's live scrobble. That's only done by the trakt addon. I'd try forcing a sync with trakt in umbrella, clearing cache and trying it again. If it continues you may want to reach out to the trakt addon developers about scrobble feature.

**Comment by umbrellaplug** [comment]
> > After some research, this is caused by the trakt addon. Sorry to keep pointing fingers at other addons here, but it was tough for me to track this down as that's not a functionality I provide. That's live scrobble. That's only done by the trakt addon. I'd try forcing a sync with trakt in umbrella, clearing cache and trying it again. If it continues you may want to reach out to the trakt addon developers about scrobble feature.
> 
> Ah right ok, thanks so much for taking the time to look into it for me. I will give that a try and see if that works, if not I will see if I can speak to the trakt addon developers about it. Do you think maybe disabling the trakt addon and enable scrobbling in umbrella itself may solve the problem? 
> 
> Thanks again for all your help. Really appreciate it. 

It wouldn't help in this scenario as umbrella doesn't support live scrobble like that. The scrobble on umbrella is for marking times when stopped and paused for resuming later on from any device where the trakt addon does it second by second which triggers that now playing popup. I had never seen that in my trakt because I didn't use their addon. Once added I immediately got the now playing on my app and website. One interesting thing to note though was I did not get a popup of the wrong item. My now playing showed the correct show every time in my testing this morning. I'm on 20.1 on Android shield.

**Comment by leemacca13** [comment]
> > > After some research, this is caused by the trakt addon. Sorry to keep pointing fingers at other addons here, but it was tough for me to track this down as that's not a functionality I provide. That's live scrobble. That's only done by the trakt addon. I'd try forcing a sync with trakt in umbrella, clearing cache and trying it again. If it continues you may want to reach out to the trakt addon developers about scrobble feature.
> > 
> > Ah right ok, thanks so much for taking the time to look into it for me. I will give that a try and see if that works, if not I will see if I can speak to the trakt addon developers about it. Do you think maybe disabling the trakt addon and enable scrobbling in umbrella itself may solve the problem? 
> > 
> > Thanks again for all your help. Really appreciate it. 
> 
> It wouldn't help in this scenario as umbrella doesn't support live scrobble like that. The scrobble on umbrella is for marking times when stopped and paused for resuming later on from any device where the trakt addon does it second by second which triggers that now playing popup. I had never seen that in my trakt because I didn't use their addon. Once added I immediately got the now playing on my app and website. One interesting thing to note though was I did not get a popup of the wrong item. My now playing showed the correct show every time in my testing this morning. I'm on 20.1 on Android shield. 

That's so strange that you didn't get the wrong item pop up, honestly have no clue what it could be, but thanks again for looking into it for me. I've disabled the trakt addon for now and have been using umbrella to scrobble instead as not having live scrobbling isn't a problem and it seems to be tracking just the shows I'm watching now and not random movies as well.
